// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/client/sftp_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "github.com/arunvelsriram/sftp-exporter/pkg/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSFTPClient is a mock of SFTPClient interface
type MockSFTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockSFTPClientMockRecorder
}

// MockSFTPClientMockRecorder is the mock recorder for MockSFTPClient
type MockSFTPClientMockRecorder struct {
	mock *MockSFTPClient
}

// NewMockSFTPClient creates a new mock instance
func NewMockSFTPClient(ctrl *gomock.Controller) *MockSFTPClient {
	mock := &MockSFTPClient{ctrl: ctrl}
	mock.recorder = &MockSFTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSFTPClient) EXPECT() *MockSFTPClientMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockSFTPClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close
func (mr *MockSFTPClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSFTPClient)(nil).Close))
}

// FSStats mocks base method
func (m *MockSFTPClient) FSStats() (model.FSStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FSStats")
	ret0, _ := ret[0].(model.FSStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FSStats indicates an expected call of FSStats
func (mr *MockSFTPClientMockRecorder) FSStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FSStats", reflect.TypeOf((*MockSFTPClient)(nil).FSStats))
}

// ObjectStats mocks base method
func (m *MockSFTPClient) ObjectStats() (model.ObjectStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectStats")
	ret0, _ := ret[0].(model.ObjectStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectStats indicates an expected call of ObjectStats
func (mr *MockSFTPClientMockRecorder) ObjectStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectStats", reflect.TypeOf((*MockSFTPClient)(nil).ObjectStats))
}
