version: "3.3"

services:
  sftp-basic:
    container_name: sftp-basic
    hostname: sftp-basic
    image: atmoz/sftp
    ports:
      - "2220:22"
    command: foo:password:::upload1,upload2
  sftp-key:
    container_name: sftp-key
    hostname: sftp-key
    image: atmoz/sftp
    ports:
      - "2221:22"
    command: foo::::upload1,upload2
    volumes:
      - "$PWD/ssh/key_without_passphrase.pub:/home/foo/.ssh/keys/key_without_passphrase.pub"
      - "$PWD/ssh/key_with_passphrase.pub:/home/foo/.ssh/keys/key_with_passphrase.pub"
  sftp-basic-and-key:
    container_name: sftp-basic-and-key
    hostname: sftp-basic-and-key
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: foo:password:::upload1,upload2
    volumes:
      - "$PWD/ssh/key_without_passphrase.pub:/home/foo/.ssh/keys/key_without_passphrase.pub"
      - "$PWD/ssh/key_with_passphrase.pub:/home/foo/.ssh/keys/key_with_passphrase.pub"
      - "$PWD/ssh/sshd_config:/etc/ssh/sshd_config"
  sftp-exporter:
    container_name: sftp-exporter
    hostname: sftp-exporter
    build:
      context: ../
      dockerfile: ./build.Dockerfile
    ports:
      - "8081:8080"
    environment:
      BIND_ADDRESS: 0.0.0.0
      LOG_LEVEL: debug
      SFTP_HOST: sftp-basic-and-key
      SFTP_PORT: 22
      SFTP_USER: foo
      SFTP_PASSWORD: password
      SFTP_PATHS: "/upload1 /upload2"
      SFTP_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMTI4LUNCQyxDQjg1MEMwODY3RDMzQkYxMDlCRTI1RDczRjJDNkE1NwoKNzV1MEFoaGQ0R2VWTHQrTmtmd0VVeDhUaXlHUFRmNStnRlhPUFNvSTk2YnpjWng4OXV5c1oxMzg4cmYvekZEaQpxT3A0cWowMFk0MFFKWnZvZThMLy8ySm0rY1JUM1dzNE8rRTRhZlYvZjNXVUZaWnpacUFrUzZsR2pqaS9ka2cvCkN0dUNMaHJWcVdaeXFoaG12T2Nyblc4TUFkOG11WVd5Nmt0SUo2SEszbDk2SDQ2N2NWU01UTTJTa2MvV0VFekQKN3orVW02MDFMQWFTa0dLRm1SK0c1dzk1WHc5WGtRQ21VSnhFR01pNlo4M3M0NU82Q20xR1Bpdnc0aWpicGNZegpxVWxQVk1ZQ3FTbXZRcGl0TFJaelAvU1NRUEZ1STBHbU5wemNtT2llYXlZUlhKRWF4TnVtZEdOK3RqR2R4bUw4CmxJelFWTkhFTENRUTAvVXJBUjFMRUNpcU1aMkloY2NKend3WEQrNGgzNjl4RDcxMlNJL3YyUUppVWowSld1aUwKVzdQbGxkVlp1TGdadGtHSEZ4dThSK1J3a1Q3VklkT2NvSEt1MkozbUdxSnFZQjVHRU9kRnlIQkhwbUYwRFlkTwpxYmJuTk9UNVlJVHFNOHhDSlVKT0JjWkhodUk5YWVwcURTT0lncUhWMFFNQUE3ZHQrZ1dkYld2bFl2S0xiMnNtCnZJUFNIZjI2VWVxTGZNdXFLQlduV09JOStTZUNTazcxWGZwRjFMOGY2amU5aGhQOWsvK3RiNG5VaGpVYzZ6TnQKc3Jtb1ovdG94ZzR1YjFQendjRjYrMkxNSE9Scm1HTzl4UStldnhlbnkwZUZOZjZBRmlZeWlwanhuOW5ZdThNYgpqQXROS1NHUEdZOS9HUDdITENWWUQxNE1qVzljdzlrS25RNkVvZkpadVVOdXRxWWRhUlczM3RoeVBINVBMa3FSClNPY2dDdWxDQzdPOHJ4Z0RKcTlDUzhZUTQ0anNhZzFORUVwbU5HSzc3R1ZqRHczQ0dwY05FZFBZVHlndUs2dTQKN1lnWVQvdWQybVlyY0lQeEdVQzFTR2pGaHc0b2QyeXFDZ2RsZGJablZPOXRUbjBzTDNGa0JzdUFMUnJsWW50VgpMbFRUQlByYVR4aXNYTlF6Y0JncGNqSldjeXlEZUlVSU1RZnFBcVBOOTNRT0p1T1VJS1I3VGhyOG5sS0w3ZkZGCks0Z1hCUGsveWVwaXlZdVlWS2YyV0xXaTBhWUkwMVdJYTlacnloc2Fwb2VaaVVxSTJ1aDRScEh0dTlndUk1UUcKbnFZMmp3MjF2Y3lEUnVtWlAwUHh0cTFqZnl0R0xQTUlsQkxCRmVGazhiZHJOeFg1S2pXWnJ0dXhyM1E4cmlMTQpsVjBIZkx5WVlCUEowKzcwZFcxS2JUT2NmOWd4U0xUVFQ2b3hHeEk2ZXBXbVlSR2lZbkVoam9ncE5BM1VOS1Z3CmZUOHpwYkp6S1V4MFI3RHg5LzV6UEVmK1JCVGNWb3VkcGlteG1qV2tGak9mOHJmVTJ1OHRRYXJ2UlpqU0gycmIKRTROeXNPU2VPZ2xDNFdWSm1WMkZFQUpOTVo3RDRVUkF1TVRmMkVCOTI5bVF2Uk82SzJZQ2dMMW5JV1J5ejdrbQpmQlRyMmFGT0lZbHRvWWdhNW9XMG9xMkE2ZThEZ0ZNcUx0aFJkQU1MazFOWkZZUUpKekJxL3M5RUNhRlI2RFBsCi9jYnF4L29idnh6R3VUWUxFaVEzVG1wVXNmMkFzbjF0TCtZd29IQVprNXNYdkhWeWR4aE9vMHZxNXY3UXZuOXMKRFFFU3p4WHU0RytON1M5UlhpL3IrZmpDdzAyMWR0U0hreFJsbDhYTkhlaWlaK2NvbzJNd29PcHJWbTJxQmhZSgpwR0poVEZrWWtud0tTa1FzRm9jNDNQdGhpTGFJSm9mOWJkM05NVENHcGw4bCtvSkhFSVdJSFBjTUsyQURlYUd4CldhRUFwZHNLVFZFUndpQ3EyTXErRGVjQXp4R25hMkZjQ1M0eDQ4cDBNKzFRMWZBdFNBLzI2R3JxbU16YXpHWW4KVTdUMEFxL3NDTFdSVUVWWXhOcFdJdE8zRzI4cmlCWUtHdFc2djJuWHFpd2IrVi95ZDF2RHlFZDREZkkrWCswMwpkcWRhYytTd0hTS3N3YVNXTTc0Y3piYTJjV09RL2dYOENIQUF5Z3RGRENIUFByNndNMUVqZ2JoN3dYZ3hiMTNECk9FQmRjN2lIMmlYeUl0V3VkVTBDbEFLcmxNcE9nVnlHTE95bkRrWk5vUTFQU1RKWUtDbS83MFN0NkZUWmxSb1AKY3VvRkVSb0hTSVcrQVdacTNlLzBiT1JJQmJPVHBuQkFqNzZlMEVkK3VuV0dheEk3Wnk5eEdrdjB3U2RwN2ZJbQpjSnVkQkRXSGM5UFloM1NJVE9PRFdFbjQ3R04vcSt5NnhUZnJkaC9TSVhHaU1WZFBiYnFIZmdlWDFUOXZ2eHNwCkIwY1JmUE1UbzRYUm8zVnRQVUJZRkRFa1ZFdlBWbldXWWZWSFlNSmNGcENxNFRQbXlQQ1FMdzNWSENFaVRHcUoKemRyRlg3Wis0dmlQWWJxb3FkZlZRcFlFY0prQzEvV1Z0NkJJR1QyY00wTHlsbkdTSXVTbkcyV0pZemd3UnRlZAo3ZHY4ZWxiYzlTS1M2UG9Cck8yS0IxT2N5TUhiYzUxK2svRGJCa0hrNzdMV2Q5T1haazJpRUtXS0VESS9uN0E5CjR0NXEvTjNjUkJPRWN3Y0h4NFVkY1FCZkhUWGlIU0ZzVjA0ck9YUUtBL21jcU9qN1Y4TVBsRDQ5U210TjJlaHgKM2NxU1p0QjFlSUNoNkZ2NW1nWnZ5bUg0SzNmRWNnTm5mU3N0MHhtNlRiZDJXSG5HcGJ1OUpoeDUwTTh4SWFmUQpndlBjR0NFdXRhclpKdXlFUFFuWkF2SDk0OXgvTGhyQm9MTGVYbE80a0Z1eFo5Zm5xaktBY0dMTlY0SjNZc3RmCmhqNlZHMjFSbzdObTFXMTd4R0hMd2tzaHZYY2pKVkUrR1Q4Z3ZHSEVHVWdQa09vdVFPdzZlM2pvR2hnWUYxaFIKMFJleVJkU0tPTzJZUFVmV09qK0pPbDVFeE44bkVRcXBrVEtMcnl1eWQzYnNuRTBtRnBnQVpwc0t3eTRHVzlpVApaNEhkd2k0MnJNL0VFMGJtaTdzeSt2azFLM0l1V09iaEJ1RXJTeGlKUnRCbjVIM252c21jQm5RaENRTWxwRWltCmNHaDdFaGhFWnlLZVRyRzlvai9sMXJXZWlvdDMwWkVNdGtWV0wxWnVRU1Z6elZZQ2ZWemxCL3lSSlZNbm1nM1IKSjFuVDd3dHVnNEdSeElkRTNGV1JoZUxPRmM2eEp4OUFBb1BmaVU0YWN3WS8vODV2M3MxeHV5OE01L2NOTExmdApSVFQwNVhyQ05wVTRVZWd1SjJuRGh5b21oSkYxTjYrU3VXMi9BL3JSQXZydTJ5RWc4VThFQ2k1cmhJVzg2YzV5CkNwRnFHa2hTNzYvNzl1V3l2YlUyOTlWb0k1eWh5Tmp6Q2tRYjMwYncwbDNyUFNuUXQ3YWt2R0lyempIODBicWQKaWFNM2J5dXpXSkVlb3pDVElUdFkyckUxc0s2NERuMnNORkQ0TTJ3VlpoNm1ZWHNQNFBJNjRCRzZqSU9JMS9zaApjQzhhZ2ZGUG8yNmZrNWRhc0NFOXNwYkFtbHE4K3dZRmU1YjlGQTZMTlpLUDkrRUtaSmQ3Um9Sd0IzQWQ2SzdjCm4wZzhDcmw1RlM3dXVOc1hFb0NrZUNyUXV4WVh5L0NMTGduckQ4MHhreHh1S2hHdlUzRjRjZFNCelBYVHNiOEEKSnJKS2Y3WWp2OUF3a3hJRVRWZlo3RmExOXZCb0NXcVFNQUNnMDFuRGxBNUdWTnB0dnBwaHBoa0lxazlkaWdoUQpVUk13djJlOElWSmNYMWF2YjBzZFY0YjROK0wvZHk0QnZyUTBYYWhSa1FHRHVqSnc0bm85NHM3blg3Rmc5NGhWCkNwaCtKTDJCZlB5MTFJMERGNUNCK1RZem11ZVpmdnZIRVh0aFFGc2cveC9IZ0dQbHFxRUJBd29uc2h2QjN5NUoKZWxMY2hpaUl1aFFzNHE2Rm1mOFg4MkxQcWxFZzVkMkFKSnU0YmdDbGFhbHBwZ2ptZ3J5MFBGaHRKSVNPSm1wQgotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      SFTP_KEY_PASSPHRASE: password
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    ports:
      - "9090:9091"
    volumes:
      - "$PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/grafana/provisioning:/etc/grafana/provisioning"
      - "$PWD/grafana/dashboards/SFTP-1621083257598.json:/var/lib/grafana/dashboards/SFTP-1621083257598.json"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
