name: "Build and Release"

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check - fmt, lint and test
        run: make check
        
      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check --config .goreleaser.yml
          
      - name: Build Docker image
        run: docker build -t sftp-exporter:latest -f Dockerfile .
        
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sftp-exporter:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            arunvelsriram/sftp-exporter:latest
            arunvelsriram/sftp-exporter:${{ github.ref_name }}
