name: "Continuous Integration"

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check - fmt, lint and test
        run: make check
      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check --config .goreleaser.yml
      - name: Build Docker image
        run: docker build -t sftp-exporter:latest -f Dockerfile .
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sftp-exporter:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
